# CHAPTER 5 : Understand Your Data With Descriptive Statistics

## *Import Library

In [7]:
import pandas as pd
import numpy as np

## 5.1 Peek at Your Data

In [35]:
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

In [ ]:
Các tiêu đề trên tương tự với từng cột ở dưới

In [36]:
df = pd.read_csv("pima-indians-diabetes.data.csv");

In [37]:
df.head(20)

,preg,plas,pres,skin,test,mass,pedi,age,class
0,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
1,6,148,72,35,0,33.6,0.627,50,1
2,1,85,66,29,0,26.6,0.351,31,0
3,8,183,64,0,0,23.3,0.672,32,1
4,1,89,66,23,94,28.1,0.167,21,0
5,0,137,40,35,168,43.1,2.288,33,1
6,5,116,74,0,0,25.6,0.201,30,0
7,3,78,50,32,88,31,0.248,26,1
8,10,115,0,0,0,35.3,0.134,29,0
9,2,197,70,45,543,30.5,0.158,53,1
10,8,125,96,0,0,0,0.232,54,1
11,4,110,92,0,0,37.6,0.191,30,0
12,10,168,74,0,0,38,0.537,34,1
13,10,139,80,0,0,27.1,1.441,57,0
14,1,189,60,23,846,30.1,0.398,59,1
15,5,166,72,19,175,25.8,0.587,51,1
16,7,100,0,0,0,30,0.484,32,1
17,0,118,84,47,230,45.8,0.551,31,1
18,7,107,74,0,0,29.6,0.254,31,1
19,1,103,30,38,83,43.3,0.183,33,0

Sử dụng head(x) để lấy ra được x dòng trong file csv được đọc

## 5.2 Dimensions of Your Data

In [20]:
df.shape

(768, 9)

Cho biết số dòng và cột của file csv mà được pd đọc

## 5.3 Data Type For Each Attribute

In [26]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

## 5.4 Descriptive Statistics

In [39]:
column_names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
df = pd.read_csv("pima-indians-diabetes.data.csv", names=column_names, header=0)

In [41]:
# Đưa ra các mô tả sơ lược về dữ liệu
df.describe()

,preg,plas,pres,skin,test,mass,pedi,age,class
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

## 5.5 Class Distribution (Classification Only)

In [42]:
df.groupby('class').size()

class
0    500
1    268
dtype: int64

## 5.6 Correlations Between Attributes

In [44]:
df.corr()

,preg,plas,pres,skin,test,mass,pedi,age,class
preg,1.000000,0.129459,0.141282,-0.081672,-0.073535,0.017683,-0.033523,0.544341,0.221898
plas,0.129459,1.000000,0.152590,0.057328,0.331357,0.221071,0.137337,0.263514,0.466581
pres,0.141282,0.152590,1.000000,0.207371,0.088933,0.281805,0.041265,0.239528,0.065068
skin,-0.081672,0.057328,0.207371,1.000000,0.436783,0.392573,0.183928,-0.113970,0.074752
test,-0.073535,0.331357,0.088933,0.436783,1.000000,0.197859,0.185071,-0.042163,0.130548
mass,0.017683,0.221071,0.281805,0.392573,0.197859,1.000000,0.140647,0.036242,0.292695
pedi,-0.033523,0.137337,0.041265,0.183928,0.185071,0.140647,1.000000,0.033561,0.173844
age,0.544341,0.263514,0.239528,-0.113970,-0.042163,0.036242,0.033561,1.000000,0.238356
class,0.221898,0.466581,0.065068,0.074752,0.130548,0.292695,0.173844,0.238356,1.000000

## 5.7 Skew of Univariate Distributions

In [46]:
df.skew()

preg     0.901674
plas     0.173754
pres    -1.843608
skin     0.109372
test     2.272251
mass    -0.428982
pedi     1.919911
age      1.129597
class    0.635017
dtype: float64